go build

cat examples/example00.txt
./ascii-art --reverse=examples/example00.txt
echo -------------------------------------------------
cat examples/example01.txt
./ascii-art --reverse=examples/example01.txt
echo -------------------------------------------------
cat examples/example02.txt
./ascii-art --reverse=examples/example02.txt
echo -------------------------------------------------
cat examples/example03.txt
./ascii-art --reverse=examples/example03.txt
echo -------------------------------------------------
cat examples/example04.txt
./ascii-art --reverse=examples/example04.txt
echo -------------------------------------------------
cat examples/example05.txt
./ascii-art --reverse=examples/example05.txt
echo -------------------------------------------------
cat examples/example06.txt
./ascii-art --reverse=examples/example06.txt
echo -------------------------------------------------
cat examples/example07.txt
./ascii-art --reverse=examples/example07.txt
echo -------------------------------------------------
cat examples/example08.txt
./ascii-art --reverse=examples/example08.txt
echo -------------------------------------------------
cat examples/example09.txt
./ascii-art --reverse=examples/example09.txt
echo -------------------------------------------------
cat examples/example10.txt
./ascii-art --reverse=examples/example10.txt
echo -------------------------------------------------
cat examples/example11.txt
./ascii-art --reverse=examples/example11.txt
echo -------------------------------------------------
cat examples/example12.txt
./ascii-art --reverse=examples/example12.txt